version: "3"
services:
  adminer:
    image: dockette/adminer:full
    container_name: adminer
    restart: always
    ports:
      - 8000:80
    networks:
      - skynet
  db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./.docker/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - skynet
networks:
  skynet:
    driver: bridge
